### PR TITLE
To avoid the blocking client call  Set Redis connection Time out 

### PR DESCRIPTION
**Pull request by MMohan1**
Added the socket time out for redis.

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Hi @MMohan1, thanks for the pull request! However, it needs several improvements before it can be merged.

* Explain the problem you're trying to solve with this change, and how this change solves it.
* Make the timeout value configurable.
* Add at least one automated test for this timeout value.
* Make sure all the automated tests pass.
* Add some documentation for how to configure this value.

I know that other people using this project have run into problems with the Python client not disconnecting from Redis correctly; if this code change solves that problem, that would be wonderful! But right now, I don't understand what this change is supposed to actually _do_.

**Comment by MMohan1** [comment]
@singingwolfboy please find below details-
**Problem** -> We are implemented the SSE events on our prod app, We faced issue that if we hit multiple time more the 15 times application got stuck and didn't got any response. 
Our Application have below config-
Nginx as Proxy Server
Twisted as wsgi to Run Flask App

**Issue** -> When i debugged this issue i find out that when we are calling the /stream endpoint it's tring to listen the Redis messages using below code 
`for pubsub_message in pubsub.listen()`
here the  `pubsub.listen()` is a blocking call until didn't got any message. In this case the Flask one thread got busy with this operation, if we hit multiple time all the flask app thread will be busy with the given operation. So the app will be unreachable in some time.

**Solution** -> While we are making connection to Redis we need to provide the socket_timeout to timeout the listen operation after certain time.
For more details go through here - https://github.com/andymccurdy/redis-py/issues/225

I am looking on unittest case, will update you on this

**Comment by arshak** [comment]
I'm seeing the same issue, unless the timeout is set a lot of zombie connections stay open to Redis.  

Here is a [load test](https://www.dropbox.com/s/0jh28u4ksf4x1zf/Screenshot%202018-11-17%2014.14.18.png?dl=0) I did with locust.  Hours later, the connections are still there and PUBSUB NUMSUB is 300

There is a connect limit of 65k with my provider (https://cloud.google.com/memorystore/docs/reference/redis-configs) so I will eventually just run out of connections.

@MMohan1's version doesn't seem to have the same problem.

**Comment by cdcformatc** [comment]
I was seeing the same issue with clients not disconnecting, setting the socket_timeout and catching the redis.exception.TimeoutError in the `messages` method as in this change request fixed it.

However if I could add a suggestion, instead of `yield []` it would be useful to yield `yield Message({}, type='timeout')` this way the client can add a listener for a 'timeout' message and do something, in my case it would be to reconnect, but zombie clients would still be killed off.  

I would very much like this pull request to be accepted as it solves many problems. I am not sure how to write a unit test for a redis timeout using the mockredis object.

**Comment by singingwolfboy** [comment]
Since the author of this pull request still hasn't provided any automated tests, or added any documentation to the Sphinx docs, I'm closing this pull request. If someone else wants to send a new pull request that meets the requirements for getting merged, I'm happy to take a look at it!

**Pull request closed without merging**
